# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

variables:
  solution: '**/*.slnx'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: BuildJob
        pool:
          vmImage: "windows-latest"

        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'


  - stage: TerraformDev
    displayName: Terraform Dev Infra
    dependsOn: Build
    jobs:
      - deployment: 
        displayName: Create Dev Infra
        pool:
          vmImage: 'windows-latest'
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@1
                  displayName: Terraform Tool Installer
                  inputs:
                    terraformVersion: 'latest'

                - task: AzureCLI@3
                  displayName: Terraform Init
                  inputs:
                    connectionType: 'azureRM'
                    azureSubscription: '<your-azure-service-connection>'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd NetflixEnglishMovies/terraform
                      terraform init -reconfigure -backend-config="backend-dev.conf"
                - task: AzureCLI@3
                  displayName: Terraform Apply
                  inputs:
                    connectionType: 'azureRM'
                    azureSubscription: '<your-azure-service-connection>'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd NetflixEnglishMovies/terraform
                      terraform apply -var-file="dev.tfvars" -auto-approve
  - stage: DeploytoDev
    displayName: Deploy to Dev Infra
    dependsOn: TerraformDev
    jobs:
      - deployment: 
        displayName: Deploy to Dev
        pool:
          vmImage: "windows-latest"
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureRmWebAppDeployment@5
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: '<your-azure-service-connection>'
                    appType: 'webApp'
                    WebAppName: 'nfenglishdevapp1'
                    packageForLinux: '$(Pipeline.workspace)/drop/**/*.zip'

  - stage: TerraformQA
    displayName: Terraform QA Infra
    dependsOn: DeploytoDev
    jobs:
      - deployment: 
        displayName: Create QA Infra
        pool:
          vmImage: 'windows-latest'
        environment: QA
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@1
                  displayName: Terraform Tool Installer
                  inputs:
                    terraformVersion: 'latest'

                - task: AzureCLI@3
                  displayName: Terraform Init
                  inputs:
                    connectionType: 'azureRM'
                    azureSubscription: '<your-azure-service-connection>'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd NetflixEnglishMovies/terraform
                      terraform init -reconfigure -backend-config="backend-qa.conf"
                - task: AzureCLI@3
                  displayName: Terraform Apply
                  inputs:
                    connectionType: 'azureRM'
                    azureSubscription: '<your-azure-service-connection>'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd NetflixEnglishMovies/terraform
                      terraform apply -var-file="qa.tfvars" -auto-approve
  - stage: DeploytoQA
    displayName: Deploy to QA Infra
    dependsOn: TerraformQA
    jobs:
      - deployment: 
        displayName: Deploy to QA
        pool:
          vmImage: "windows-latest"
        environment: QA
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureRmWebAppDeployment@5
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: '<your-azure-service-connection>'
                    appType: 'webApp'
                    WebAppName: 'nfenglishqaapp1'
                    packageForLinux: '$(Pipeline.workspace)/drop/**/*.zip'